// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.example.model.security;

import com.example.model.security.Principal;
import com.example.model.security.PrincipalDataOnDemand;
import com.example.model.security.PrincipalIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PrincipalIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PrincipalIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PrincipalIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PrincipalIntegrationTest: @Transactional;
    
    @Autowired
    private PrincipalDataOnDemand PrincipalIntegrationTest.dod;
    
    @Test
    public void PrincipalIntegrationTest.testCountPrincipals() {
        Assert.assertNotNull("Data on demand for 'Principal' failed to initialize correctly", dod.getRandomPrincipal());
        long count = Principal.countPrincipals();
        Assert.assertTrue("Counter for 'Principal' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PrincipalIntegrationTest.testFindPrincipal() {
        Principal obj = dod.getRandomPrincipal();
        Assert.assertNotNull("Data on demand for 'Principal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Principal' failed to provide an identifier", id);
        obj = Principal.findPrincipal(id);
        Assert.assertNotNull("Find method for 'Principal' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Principal' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PrincipalIntegrationTest.testFindAllPrincipals() {
        Assert.assertNotNull("Data on demand for 'Principal' failed to initialize correctly", dod.getRandomPrincipal());
        long count = Principal.countPrincipals();
        Assert.assertTrue("Too expensive to perform a find all test for 'Principal', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Principal> result = Principal.findAllPrincipals();
        Assert.assertNotNull("Find all method for 'Principal' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Principal' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PrincipalIntegrationTest.testFindPrincipalEntries() {
        Assert.assertNotNull("Data on demand for 'Principal' failed to initialize correctly", dod.getRandomPrincipal());
        long count = Principal.countPrincipals();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Principal> result = Principal.findPrincipalEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Principal' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Principal' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PrincipalIntegrationTest.testFlush() {
        Principal obj = dod.getRandomPrincipal();
        Assert.assertNotNull("Data on demand for 'Principal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Principal' failed to provide an identifier", id);
        obj = Principal.findPrincipal(id);
        Assert.assertNotNull("Find method for 'Principal' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPrincipal(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Principal' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PrincipalIntegrationTest.testMergeUpdate() {
        Principal obj = dod.getRandomPrincipal();
        Assert.assertNotNull("Data on demand for 'Principal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Principal' failed to provide an identifier", id);
        obj = Principal.findPrincipal(id);
        boolean modified =  dod.modifyPrincipal(obj);
        Integer currentVersion = obj.getVersion();
        Principal merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Principal' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PrincipalIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Principal' failed to initialize correctly", dod.getRandomPrincipal());
        Principal obj = dod.getNewTransientPrincipal(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Principal' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Principal' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Principal' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PrincipalIntegrationTest.testRemove() {
        Principal obj = dod.getRandomPrincipal();
        Assert.assertNotNull("Data on demand for 'Principal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Principal' failed to provide an identifier", id);
        obj = Principal.findPrincipal(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Principal' with identifier '" + id + "'", Principal.findPrincipal(id));
    }
    
}
