// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.example.model.security;

import com.example.model.security.Authority;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Authority_Roo_Configurable {
    
    declare @type: Authority: @Configurable;
    
}
