// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.example.model.security;

import com.example.model.security.AuthorityPrincipalAssignment;
import com.example.model.security.AuthorityPrincipalAssignmentDataOnDemand;
import com.example.model.security.AuthorityPrincipalAssignmentIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AuthorityPrincipalAssignmentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AuthorityPrincipalAssignmentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AuthorityPrincipalAssignmentIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AuthorityPrincipalAssignmentIntegrationTest: @Transactional;
    
    @Autowired
    private AuthorityPrincipalAssignmentDataOnDemand AuthorityPrincipalAssignmentIntegrationTest.dod;
    
    @Test
    public void AuthorityPrincipalAssignmentIntegrationTest.testCountAuthorityPrincipalAssignments() {
        Assert.assertNotNull("Data on demand for 'AuthorityPrincipalAssignment' failed to initialize correctly", dod.getRandomAuthorityPrincipalAssignment());
        long count = AuthorityPrincipalAssignment.countAuthorityPrincipalAssignments();
        Assert.assertTrue("Counter for 'AuthorityPrincipalAssignment' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AuthorityPrincipalAssignmentIntegrationTest.testFindAuthorityPrincipalAssignment() {
        AuthorityPrincipalAssignment obj = dod.getRandomAuthorityPrincipalAssignment();
        Assert.assertNotNull("Data on demand for 'AuthorityPrincipalAssignment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AuthorityPrincipalAssignment' failed to provide an identifier", id);
        obj = AuthorityPrincipalAssignment.findAuthorityPrincipalAssignment(id);
        Assert.assertNotNull("Find method for 'AuthorityPrincipalAssignment' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AuthorityPrincipalAssignment' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AuthorityPrincipalAssignmentIntegrationTest.testFindAllAuthorityPrincipalAssignments() {
        Assert.assertNotNull("Data on demand for 'AuthorityPrincipalAssignment' failed to initialize correctly", dod.getRandomAuthorityPrincipalAssignment());
        long count = AuthorityPrincipalAssignment.countAuthorityPrincipalAssignments();
        Assert.assertTrue("Too expensive to perform a find all test for 'AuthorityPrincipalAssignment', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AuthorityPrincipalAssignment> result = AuthorityPrincipalAssignment.findAllAuthorityPrincipalAssignments();
        Assert.assertNotNull("Find all method for 'AuthorityPrincipalAssignment' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AuthorityPrincipalAssignment' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AuthorityPrincipalAssignmentIntegrationTest.testFindAuthorityPrincipalAssignmentEntries() {
        Assert.assertNotNull("Data on demand for 'AuthorityPrincipalAssignment' failed to initialize correctly", dod.getRandomAuthorityPrincipalAssignment());
        long count = AuthorityPrincipalAssignment.countAuthorityPrincipalAssignments();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AuthorityPrincipalAssignment> result = AuthorityPrincipalAssignment.findAuthorityPrincipalAssignmentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AuthorityPrincipalAssignment' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AuthorityPrincipalAssignment' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AuthorityPrincipalAssignmentIntegrationTest.testFlush() {
        AuthorityPrincipalAssignment obj = dod.getRandomAuthorityPrincipalAssignment();
        Assert.assertNotNull("Data on demand for 'AuthorityPrincipalAssignment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AuthorityPrincipalAssignment' failed to provide an identifier", id);
        obj = AuthorityPrincipalAssignment.findAuthorityPrincipalAssignment(id);
        Assert.assertNotNull("Find method for 'AuthorityPrincipalAssignment' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAuthorityPrincipalAssignment(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'AuthorityPrincipalAssignment' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AuthorityPrincipalAssignmentIntegrationTest.testMergeUpdate() {
        AuthorityPrincipalAssignment obj = dod.getRandomAuthorityPrincipalAssignment();
        Assert.assertNotNull("Data on demand for 'AuthorityPrincipalAssignment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AuthorityPrincipalAssignment' failed to provide an identifier", id);
        obj = AuthorityPrincipalAssignment.findAuthorityPrincipalAssignment(id);
        boolean modified =  dod.modifyAuthorityPrincipalAssignment(obj);
        Integer currentVersion = obj.getVersion();
        AuthorityPrincipalAssignment merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AuthorityPrincipalAssignment' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AuthorityPrincipalAssignmentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AuthorityPrincipalAssignment' failed to initialize correctly", dod.getRandomAuthorityPrincipalAssignment());
        AuthorityPrincipalAssignment obj = dod.getNewTransientAuthorityPrincipalAssignment(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AuthorityPrincipalAssignment' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AuthorityPrincipalAssignment' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'AuthorityPrincipalAssignment' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AuthorityPrincipalAssignmentIntegrationTest.testRemove() {
        AuthorityPrincipalAssignment obj = dod.getRandomAuthorityPrincipalAssignment();
        Assert.assertNotNull("Data on demand for 'AuthorityPrincipalAssignment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AuthorityPrincipalAssignment' failed to provide an identifier", id);
        obj = AuthorityPrincipalAssignment.findAuthorityPrincipalAssignment(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AuthorityPrincipalAssignment' with identifier '" + id + "'", AuthorityPrincipalAssignment.findAuthorityPrincipalAssignment(id));
    }
    
}
