// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.example.model.security;

import com.example.model.security.Authority;
import com.example.model.security.AuthorityDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect AuthorityDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AuthorityDataOnDemand: @Component;
    
    private Random AuthorityDataOnDemand.rnd = new SecureRandom();
    
    private List<Authority> AuthorityDataOnDemand.data;
    
    public Authority AuthorityDataOnDemand.getNewTransientAuthority(int index) {
        Authority obj = new Authority();
        setRealAuthority(obj, index);
        setRoleId(obj, index);
        return obj;
    }
    
    public void AuthorityDataOnDemand.setRealAuthority(Authority obj, int index) {
        String realAuthority = "realAuthority_" + index;
        if (realAuthority.length() > 50) {
            realAuthority = realAuthority.substring(0, 50);
        }
        obj.setRealAuthority(realAuthority);
    }
    
    public void AuthorityDataOnDemand.setRoleId(Authority obj, int index) {
        String roleId = "roleId_" + index;
        if (roleId.length() > 10) {
            roleId = roleId.substring(0, 10);
        }
        obj.setRoleId(roleId);
    }
    
    public Authority AuthorityDataOnDemand.getSpecificAuthority(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Authority obj = data.get(index);
        Long id = obj.getId();
        return Authority.findAuthority(id);
    }
    
    public Authority AuthorityDataOnDemand.getRandomAuthority() {
        init();
        Authority obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Authority.findAuthority(id);
    }
    
    public boolean AuthorityDataOnDemand.modifyAuthority(Authority obj) {
        return false;
    }
    
    public void AuthorityDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Authority.findAuthorityEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Authority' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Authority>();
        for (int i = 0; i < 10; i++) {
            Authority obj = getNewTransientAuthority(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
